### ISSUE TITLE
Two arguments expected, none passed

### ISSUE THREAD

**Issue by sarfraznawaz2005** [eusonlito/laravel-Packer#10]
Packer.php line 325:

````php
$this->name = $this->checkNewer();
````

function definition is:

````php
protected function checkNewer($files, $name)
````

Since no arguments are passed, this is resulting in error mentioned in title.

**Comment by eusonlito** [comment]
Released fix on tag v2.2.1 https://github.com/eusonlito/laravel-Packer/releases/tag/v2.2.1
