### ISSUE TITLE
php artisan vendor:publish

### ISSUE THREAD

**Issue by rrroulio** [eusonlito/laravel-Packer#11]
Laravel 6.
This commandline returns :
Which provider or tag's files would you like to publish?:
... 
I tried things without success and finaly  i  done it manually, 
copy /vendor/eusonlito/laravel-packer/src/config/config.php
to /config/packer.php

**Comment by eusonlito** [comment]
Updated vendor publish command on README.md:

```
php artisan vendor:publish --provider="Eusonlito\LaravelPacker\PackerServiceProvider"
```

Thanks!
