### ISSUE TITLE
Packer doesn't track public folder

### ISSUE THREAD

**Issue by cfloresomi** [eusonlito/laravel-Packer#12]
Hello. First for all sorry for my broken english.
So I have this issue, I'm trying to deploy to my server a project, but when i run on the server instead of
`http://localhost/multicrm/public/bap/plugins/font-awesome/css/font-awesome.min.css
`It shows:
`http://localhost/bap/plugins/font-awesome/css/font-awesome.min.css
`
It doesn't reach my public folder, what should i do? 

On my Packer::css got: 
`Packer::css(['/bap/plugins/bootstrap/css/bootstrap.css','/storage/cache/css/auth.min.css')`

**Comment by eusonlito** [comment]
Do you have configured your `APP_URL` with `http://localhost/multicrm/public` on `.env` file?

**Comment by cfloresomi** [comment]
> Do you have configured your `APP_URL` with `http://localhost/multicrm/public` on `.env` file?

Yes i did it, but when i try to access in another PC, the error shows again. On my local server works, but outside doesn't

**Comment by cfloresomi** [comment]
> Do you have configured your `APP_URL` with `http://localhost/multicrm/public` on `.env` file?

I solved it, kinda i guess haha, On my `APP_URL` instead of `http://localhost` I wrote the server IP address, THANKS!

**Comment by eusonlito** [comment]
Ok!
