### ISSUE TITLE
Get forbidden error, wrong chmod

### ISSUE THREAD

**Issue by MDylan** [eusonlito/laravel-Packer#15]
Hi,

This plugin is great!
But in my case, when it create css / js files, all files are get "forbidden" error.
The file's chmod is: 600 what's wrong (not readable). 
I set it in all files manually to 644, and working well.
(System is a linux, framework: laravel 8)

**Comment by eusonlito** [comment]
Maybe do you have some custom umask settings to Apache user on your system? https://stackoverflow.com/questions/428416/setting-the-umask-of-the-apache-user?answertab=votes#tab-top

**Comment by MDylan** [comment]
I don't know, it's a shared hosting system. :(
I plugin with this line (example)
`{!! Packer::css('/dist/css/adminlte.min.css', '/dist/css/cache_adminlte.min.css') !!}`

**Comment by eusonlito** [comment]
And your provider is?

**Comment by MDylan** [comment]
I have asked my provider, and there are already set umask to 0022. 
If I create a new file manually with php fopen, it have the good permission: 644

**Comment by eusonlito** [comment]
Ok, I can add then a chmod after the file is created to fix this problem :)

**Comment by eusonlito** [comment]
Released new version `v.2.6.6` https://github.com/eusonlito/laravel-Packer/releases/tag/v2.2.6

**Comment by MDylan** [comment]
It's working now, thank you!
