### ISSUE TITLE
css minify removes need spaces

### ISSUE THREAD

**Issue by MDylan** [eusonlito/laravel-Packer#16]
I found a bug, when I use variables with calc in css and minify it.

Example:
```
.span {
left: calc(50% - var(--gap, 10px) - var(--line-width, 50px));
}
```
It's minify to this:
```
.span{left:calc(50% - var(--gap,10px)- var(--line-width,50px));}
```

The problem is, that the space between the "10px)" and "- var" is needed. 

The following is working as expected:
```
.span{left:calc(50% - var(--gap,10px) - var(--line-width,50px));}
```

Without it, chrome does not render the span correctly.

**Comment by eusonlito** [comment]
Can you test the release [3.0.0](https://github.com/eusonlito/laravel-Packer/releases/tag/v3.0.0)?

**Comment by MDylan** [comment]
> Can you test the release [3.0.0](https://github.com/eusonlito/laravel-Packer/releases/tag/v3.0.0)?

Now its work properly. Thank you for your quick response and solution!
