### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by bradley-varol** [eusonlito/laravel-Packer#5]
This package just isn't doing anything for me.  
For example, `{!! Packer::js(['/js/app.js', '/js/frontend.js'], '/storage/cache/js/app.js') !!}` just outputs the two js files that I have in my public folder already. It's not minifying them and storing in `/storage/cache/js/`, in fact there isn't even a folder being created there.  
  
Am i missing something here?

**Comment by eusonlito** [comment]
Do you have published the `config/packer.php` file?

**Comment by bradley-varol** [comment]
Yes. Do I need to change anything inside the config?

**Comment by eusonlito** [comment]
check if your current enviroment name is in `ignore_environments` on config https://github.com/eusonlito/laravel-Packer/blob/master/src/config/config.php#L18

**Comment by bradley-varol** [comment]
Oops.. It was. Assume that fixed this issue unless I comment back here (can't test at the moment). Cheers!
