### ISSUE TITLE
Problem with base64 images

### ISSUE THREAD

**Issue by laravelbap** [eusonlito/laravel-Packer#6]
Hi,
i have problem with base64 images in css files. When css file is minified by packer all base64 images are changed and prefixed with URL and file path.

packed with packer:
colorpicker-saturation{width:100px;height:100px;background-image:url(https://myurl.com/static/plugins/bootstrap-colorpicker/css/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAQAAADa613fAAAP9klEQVR4XnRWC47rNgwcKjlA0bv2VL1Qi/YELRav7203iS1ppqZoiXCAhuBHVLI74xFtG3/Hz2joIOjRGuR5eMYuRn9YA1fds859KX8Zvcz...

should be: 

colorpicker-saturation{width:100px;height:100px;background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAQAAADa613fAAAP9klEQVR4XnRWC47rNgwcKjlA0bv2VL1Qi/YELRav7203iS1ppqZoiXCAhuBHVLI74xFtG3/Hz2joIOjRGuR5eMYuRn9YA1fds859KX8Zvcz...

any idea how to solve?

**Comment by eusonlito** [comment]
And original css code?

**Comment by laravelbap** [comment]
Hi,

here is source css 

https://github.com/xdan/datetimepicker/blob/master/jquery.datetimepicker.css

i think that problem is here 
```
Eusonlito\LaravelPacker\Providers\CSS
public function pack($file, $public)
    {
        ...
        return preg_replace('/(url\([\'"]?)/', '$1'.$this->settings['asset'].dirname($public).'/', $contents);
    }

  if i will replate with only "return $contents;"  but this wont work for all other images.
..
```

**Comment by eusonlito** [comment]
Ok, it's a bug.

I think that regular expression should be something like:
```php
return preg_replace(/(url\((?![\'"]))(.*)/, '$1'.$this->settings['asset'].dirname($public).'/$2', $contents);
```

I will test it today.

Thanks!

**Comment by laravelbap** [comment]
Hi, unfortunately, this does not work. I'm not very good at regexp and this patch would be very useful for me.

**Comment by laravelbap** [comment]
Hi,
i think i fixed this. Please check! 
```
 return preg_replace( '/(url\((?!d|\'d|\"d))([\'"]?)/', '$1$2'.$this->settings['asset'].dirname($public).'/', $contents);
```

**Comment by rrroulio** [comment]
@laravelbap  Thanks. It fix my laravel6  native app.css and base64 background svg icons. 
@eusonlito   Why not add this fix in master ?

**Comment by eusonlito** [comment]
> @eusonlito Why not add this fix in master ?
Ok, let me see :)
