### ISSUE TITLE
It's always saying Missing option ignore_environments

### ISSUE THREAD

**Issue by hizbul25** [eusonlito/laravel-Packer#9]
production.ERROR: Missing option ignore_environments

**Comment by eusonlito** [comment]
And what is the value for `ignore_environments` in `config/packer.php` file?

**Comment by hizbul25** [comment]
I am using Laravel 5.8
 value for ignore_environments in config/packer.php file is `production`

**Comment by eusonlito** [comment]
Must be an array: `'ignore_environments' => ['production']`.
